# config.yaml
mysql:
  host: 192.168.31.10
  port: 3307
  user: root
  password: root
  # 具体的数据库名
  database: test
  # 是否开启删除监听: 0-关闭 1-开启
  isDel: 0
  isBox: 1
  path: /Users/sopp/Documents/compose/docker-compose-test
  file: docker-compose-test/test.sh
  backFile: backup.sh